// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/population.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/WorkWorkWork-Team/gov-ec-api/model"
	gomock "github.com/golang/mock/gomock"
)

// MockPopulationService is a mock of PopulationService interface.
type MockPopulationService struct {
	ctrl     *gomock.Controller
	recorder *MockPopulationServiceMockRecorder
}

// MockPopulationServiceMockRecorder is the mock recorder for MockPopulationService.
type MockPopulationServiceMockRecorder struct {
	mock *MockPopulationService
}

// NewMockPopulationService creates a new mock instance.
func NewMockPopulationService(ctrl *gomock.Controller) *MockPopulationService {
	mock := &MockPopulationService{ctrl: ctrl}
	mock.recorder = &MockPopulationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPopulationService) EXPECT() *MockPopulationServiceMockRecorder {
	return m.recorder
}

// GetAllCandidateInfo mocks base method.
func (m *MockPopulationService) GetAllCandidateInfo() ([]model.PopulationDatabaseRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCandidateInfo")
	ret0, _ := ret[0].([]model.PopulationDatabaseRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCandidateInfo indicates an expected call of GetAllCandidateInfo.
func (mr *MockPopulationServiceMockRecorder) GetAllCandidateInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCandidateInfo", reflect.TypeOf((*MockPopulationService)(nil).GetAllCandidateInfo))
}

// GetPopulationStatistics mocks base method.
func (m *MockPopulationService) GetPopulationStatistics() ([]model.PopulationResponseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopulationStatistics")
	ret0, _ := ret[0].([]model.PopulationResponseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopulationStatistics indicates an expected call of GetPopulationStatistics.
func (mr *MockPopulationServiceMockRecorder) GetPopulationStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopulationStatistics", reflect.TypeOf((*MockPopulationService)(nil).GetPopulationStatistics))
}
